name: npmjs

on: [push, pull_request, release]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm test
      - name: publish
        if: github.event_name == 'release' && github.event.action == 'created'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
