name: npmjs

on:
    push:
    pull_request:
    release:
        types:
            - published

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                target: ['node']
                node: ['14', '16']
                include:
                    - target: web
                      node: 16
                      browser: firefox
                    - target: web
                      node: 16
                      browser: chromium
                    - target: web
                      node: 16
                      browser: webkit
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v2
              id: cache
              with:
                  path: |
                      node_modules
                      ~/.cache/ms-playwright
                  key: ${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}
                  registry-url: https://registry.npmjs.org/
            - run: npm install -g npm@^6
            - if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci
            - if: matrix.node == '16' && matrix.browser == 'webkit'
              run: sudo npx playwright install-deps
            - run: ENV=${{ matrix.target }} BROWSER=${{ matrix.browser }} npm test
            - run: ENV=${{ matrix.target }} BROWSER=${{ matrix.browser }} npm run benchmarks
            - if: github.event_name == 'release' && github.event.action == 'published' && matrix.node == '16' && matrix.target == 'node'
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.npm_token}}
