name: npmjs

on: [push, pull_request, release]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14', '16' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm test
      - name: Run npm publish
        if: github.event_name == 'release' && github.event.action == 'created' && matrix.node == '16'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
